<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        User::create([
            'name' => 'Admin User',
            'username' => 'adminuser',
            'email' => 'admin@example.com',
            'password' => Hash::make('password'),
            'faculty' => 'Teknik',
            'department' => 'Informatika',
            'handphone' => '081234567890',
            'religion' => 'Islam',
            'gender' => true,
            'address' => 'Alamat Admin',
            'birthday' => '1985-01-01',
            'status' => true,
            'NIP' => '12345678',
            'position' => 1,
            'position_name' => 'Admin',
            'isAdmin' => true,
            'branch' => 'Bandung',
        ]);

        DB::table('users')->insert([
            [
                'id' => 12,
                'name' => 'Alice Johnson',
                'username' => 'alicej',
                'email' => 'alice.johnson@example.com',
                'password' => Hash::make('password123'),
                'faculty' => 'Computer Science',
                'department' => 'Informatics',
                'handphone' => 628123456789,
                'religion' => 'Christianity',
                'gender' => true,
                'address' => '123 Main Street, City A',
                'birthday' => '1990-01-15',
                'status' => true,
                'NIP' => 1001001,
                'position' => 1,
                'profile_picture' => 'alice.jpg',
                'position_name' => 'Lecturer',
                'isAdmin' => true,
                'branch' => 'Bandung',
            ],
            [
                'id' => 2,
                'name' => 'Bob Smith',
                'username' => 'bobsmith',
                'email' => 'bob.smith@example.com',
                'password' => Hash::make('password123'),
                'faculty' => 'Engineering',
                'department' => 'Electrical Engineering',
                'handphone' => 628123456780,
                'religion' => 'Islam',
                'gender' => true,
                'address' => '456 Second Street, City B',
                'birthday' => '1985-06-25',
                'status' => false,
                'NIP' => 1001002,
                'position' => 2,
                'profile_picture' => 'bob.jpg',
                'position_name' => 'Assistant Professor',
                'isAdmin' => false,
                'branch' => 'Bandung',
            ],
            [
                'id' => 3,
                'name' => 'Catherine Bell',
                'username' => 'cathbell',
                'email' => 'catherine.bell@example.com',
                'password' => Hash::make('password123'),
                'faculty' => 'Humanities',
                'department' => 'Literature',
                'handphone' => 628123456781,
                'religion' => 'Buddhism',
                'gender' => false,
                'address' => '789 Third Avenue, City C',
                'birthday' => '1992-03-30',
                'status' => true,
                'NIP' => 1001003,
                'position' => 3,
                'profile_picture' => 'catherine.jpg',
                'position_name' => 'Senior Lecturer',
                'isAdmin' => false,
                'branch' => 'Bandung',
            ],
            [
                'id' => 4,
                'name' => 'David Lee',
                'username' => 'davidlee',
                'email' => 'david.lee@example.com',
                'password' => Hash::make('password123'),
                'faculty' => 'Business',
                'department' => 'Management',
                'handphone' => 628123456782,
                'religion' => 'Hinduism',
                'gender' => true,
                'address' => '101 Fourth Street, City D',
                'birthday' => '1988-09-12',
                'status' => true,
                'NIP' => 1001004,
                'position' => 4,
                'profile_picture' => 'david.jpg',
                'position_name' => 'Professor',
                'isAdmin' => true,
                'branch' => 'Bandung',
            ],
            [
                'id' => 5,
                'name' => 'Emily Davis',
                'username' => 'emilyd',
                'email' => 'emily.davis@example.com',
                'password' => Hash::make('password123'),
                'faculty' => 'Education',
                'department' => 'Primary Education',
                'handphone' => 628123456783,
                'religion' => 'Christianity',
                'gender' => false,
                'address' => '202 Fifth Lane, City E',
                'birthday' => '1995-07-05',
                'status' => true,
                'NIP' => 1001005,
                'position' => 5,
                'profile_picture' => 'emily.jpg',
                'position_name' => 'Lecturer',
                'isAdmin' => false,
                'branch' => 'surabaya',
            ],
            [
                'id' => 6,
                'name' => 'Frank Miller',
                'username' => 'frankm',
                'email' => 'frank.miller@example.com',
                'password' => Hash::make('password123'),
                'faculty' => 'Computer Science',
                'department' => 'Software Engineering',
                'handphone' => 628123456784,
                'religion' => 'Islam',
                'gender' => true,
                'address' => '303 Sixth Street, City F',
                'birthday' => '1983-11-21',
                'status' => false,
                'NIP' => 1001006,
                'position' => 6,
                'profile_picture' => 'frank.jpg',
                'position_name' => 'Instructor',
                'isAdmin' => false,
                'branch' => 'Bandung',
            ],
            [
                'id' => 7,
                'name' => 'Grace Brown',
                'username' => 'graceb',
                'email' => 'grace.brown@example.com',
                'password' => Hash::make('password123'),
                'faculty' => 'Science',
                'department' => 'Biology',
                'handphone' => 628123456785,
                'religion' => 'Christianity',
                'gender' => false,
                'address' => '404 Seventh Road, City G',
                'birthday' => '1991-02-17',
                'status' => true,
                'NIP' => 1001007,
                'position' => 7,
                'profile_picture' => 'grace.jpg',
                'position_name' => 'Assistant Lecturer',
                'isAdmin' => false,
                'branch' => 'Bandung',
            ],
            [
                'id' => 8,
                'name' => 'Henry Adams',
                'username' => 'henrya',
                'email' => 'henry.adams@example.com',
                'password' => Hash::make('password123'),
                'faculty' => 'Law',
                'department' => 'Criminal Law',
                'handphone' => 628123456786,
                'religion' => 'Atheism',
                'gender' => true,
                'address' => '505 Eighth Blvd, City H',
                'birthday' => '1980-10-01',
                'status' => true,
                'NIP' => 1001008,
                'position' => 8,
                'profile_picture' => 'henry.jpg',
                'position_name' => 'Lecturer',
                'isAdmin' => false,
                'branch' => 'Bandung',
            ],
            [
                'id' => 9,
                'name' => 'Isabel Thomas',
                'username' => 'isabelt',
                'email' => 'isabel.thomas@example.com',
                'password' => Hash::make('password123'),
                'faculty' => 'Medicine',
                'department' => 'General Medicine',
                'handphone' => 628123456787,
                'religion' => 'Islam',
                'gender' => false,
                'address' => '606 Ninth Lane, City I',
                'birthday' => '1994-05-14',
                'status' => true,
                'NIP' => 1001009,
                'position' => 9,
                'profile_picture' => 'isabel.jpg',
                'position_name' => 'Senior Lecturer',
                'isAdmin' => false,
                'branch' => 'Jakarta',
            ],
            [
                'id' => 10,
                'name' => 'Jack Wilson',
                'username' => 'jackw',
                'email' => 'jack.wilson@example.com',
                'password' => Hash::make('password123'),
                'faculty' => 'Architecture',
                'department' => 'Interior Design',
                'handphone' => 628123456788,
                'religion' => 'Christianity',
                'gender' => true,
                'address' => '707 Tenth Ave, City J',
                'birthday' => '1993-04-22',
                'status' => false,
                'NIP' => 1001010,
                'position' => 10,
                'profile_picture' => 'jack.jpg',
                'position_name' => 'Instructor',
                'isAdmin' => true,
                'branch' => 'Surabaya',
            ],
            [
                'id' => 11,
                'name' => 'Karen Lopez',
                'username' => 'karenl',
                'email' => 'karen.lopez@example.com',
                'password' => Hash::make('password123'),
                'faculty' => 'Arts',
                'department' => 'Fine Arts',
                'handphone' => 628123456789,
                'religion' => 'Buddhism',
                'gender' => false,
                'address' => '808 Eleventh St, City K',
                'birthday' => '1987-08-19',
                'status' => true,
                'NIP' => 1001011,
                'position' => 11,
                'profile_picture' => 'karen.jpg',
                'position_name' => 'Associate Professor',
                'isAdmin' => false,
                'branch' => 'Jakarta',
            ],
        ]);
    }
}
